sudo: required

language: php

notifications:
  email: false

php:
  - 7.1

services:
  - docker

# disable the default submodule logic
git:
  submodules: false

addons:
  apt:
    packages:
      - docker-ce

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.19.0
    - secure: "aQg9k8gfC6ZYrrIficXiEv5Rt2BWJ6dV4syxOYkiBtDR7Hl71atnuR10MZdUrt0JKMeLvnZTT0ncSVHPoEcEWKZmSoIje0HvGPPUigSnPXlyLwaC6iPF8Y/TPIiiQNostFjKzstlxvORobjB7o3yEUn/RbmDxFx9t1sWiUgfTWY="

before_install:
  - sudo service mysql stop

  # update docker
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce subversion

  # remove existing version of docker-compose and install an updated version
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

install:
  # start the global docker
  - sudo bash dev/docker/global/start.sh

  # start the square1 project docker
  - sudo bash dev/docker/start.sh

before_script:

script: