name: 'ESLint'
on:
  pull_request:
    paths:
      - 'wp-content/plugins/core/**.js'
      - 'wp-content/themes/core/**.js'
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GH_BOT_TOKEN }}
          eslint_flags: 'wp-content/plugins/core/**.js wp-content/themes/core/**.js'
