version: "3.4"

x-networks: &proxynetwork
  networks:
    - proxy

x-nginx: &nginx
  image: nginx:stable-alpine
  working_dir: /application
  environment:
    - VIRTUAL_HOST=square1.tribe,*.square1.tribe
  volumes:
    - ../..:/application/www:cached
    - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    - ./phpdocker/nginx/fastcgi.conf:/etc/nginx/fastcgi_params

x-php: &php
  build:
    context: .
    dockerfile: phpdocker/php-fpm/Dockerfile
  image: tribe-phpfpm:7.2-rev1
  working_dir: /application
  volumes:
    - ../..:/application/www:cached
    - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
    - ./phpdocker/php-fpm/ssmtp.conf:/etc/ssmtp/ssmtp.conf:ro
    - ./wp-cli.yml:/application/wp-cli.yml
    - ./composer:/application/.composer
  dns: 172.20.10.250
  links:
    - memcached
    - redis
    - elasticsearch
  external_links:
    - "tribe-mysql:mysql"
    - "tribe-mail:mail"
  environment:
    - COMPOSER_ALLOW_SUPERUSER=1
    - COMPOSER_HOME=/application/.composer
    - PAGER=more
    - PHP_IDE_CONFIG=serverName=square1.tribe

services:

    redis:
      <<: *proxynetwork
      image: redis:alpine

    elasticsearch:
      <<: *proxynetwork
      image: docker.elastic.co/elasticsearch/elasticsearch:5.2.2
      environment:
        - cluster.name=square1
        - xpack.security.enabled=false
        - bootstrap.memory_lock=true
        - script.inline=false
        - script.stored=false
        - script.file=true
        - script.engine.mustache.inline.search=true
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      ulimits:
        memlock:
          soft: -1
          hard: -1
        nofile:
          soft: 65536
          hard: 65536
      ports:
        - "9200"
      volumes:
        - ./elasticsearch/data:/usr/share/elasticsearch/data:delegated

    memcached:
      <<: *proxynetwork
      image: memcached:alpine

    php-fpm:
      <<: *proxynetwork
      <<: *php

    webserver:
      <<: *proxynetwork
      <<: *nginx
      links:
        - php-fpm

networks:
  proxy:
    external:
      name: global_proxy


