version: "3.3"
services:

    rabbitmq:
      image: "rabbitmq:3-management-alpine"
      environment:
        RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
        RABBITMQ_DEFAULT_USER: "rabbitmq"
        RABBITMQ_DEFAULT_PASS: "rabbitmq"
        RABBITMQ_DEFAULT_VHOST: "/"
      volumes:
        - "./rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins"
      networks:
        - proxy
      labels:
        - "traefik.frontend.rule=Host:rabbitmq.tribe"
        - "traefik.docker.network=proxy"
        - "traefik.port=15672"

    redis:
      image: redis:alpine
      labels:
        - "traefik.enable=false"
      networks:
        - proxy

    elasticsearch:
      image: elasticsearch:5.3-alpine
      labels:
        - "traefik.enable=false"
      networks:
        - proxy

    memcached:
      image: memcached:alpine
      labels:
        - "traefik.enable=false"
      networks:
        - proxy

    php-fpm:
      build:
        context: .
        dockerfile: phpdocker/php-fpm/Dockerfile
      labels:
        - "traefik.enable=false"
      working_dir: /application
      networks:
        - proxy
      dns: 172.20.10.250
      volumes:
        - ../..:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.0/fpm/conf.d/99-overrides.ini
      links:
        - memcached
        - redis
        - elasticsearch
      external_links:
        - "tribe-mysql:mysql"
        - "tribe-mail:mail"

    webserver:
      image: nginx:alpine
      working_dir: /application
      labels:
        - "traefik.frontend.rule=Host:project-name.tribe"
        - "traefik.docker.network=proxy"
      volumes:
        - ../..:/application
        - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      networks:
        - proxy
      links:
        - php-fpm

networks:
  proxy:
    external:
      name: global_proxy